INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('1', 'Semenov','Alexandr','Andreevich','2063');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('1', '1','3','0','1995-01-25','man',
'non-working','20','2013-03-17');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('2', 'Peterova','Anna','Andreevna','1586');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('2', '2','1','0','1973-11-20','woman','teacher','25','2016-11-05');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('3', 'Ivanov','Alexandr','Ivanovich','8184');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('3', '3','4','0','1983-6-17','man','teacher','16','2008-01-14');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('4', 'Semenov','Ivan','Alexandrovich','4784');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('4', '4','1','1','1963-6-05','man','deputate','36','2013-11-01');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('5', 'Semenova','Galina','Ivanovna','5967');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('5', '5','4','1','1987-03-05','woman','RNPC','23','2014-01-01');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('6', 'Andreeva','Maria','Semenovna','4119');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('6', '6','3','0','1988-01-05','woman','non-working','24','2017-01-14');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('7', 'Ivanova','Sophiya','Peterovna','4128');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('7', '7','1','0','1982-9-01','woman','driver','5','2011-6-01');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('8', 'Semenova','Maria','Ivanovna','5746');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('8', '8','3','1','1976-6-01','woman','teacher','22','2007-01-25');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('9', 'Semenova','Anna','Peterovna','8568');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('9', '9','4','1','1987-01-05','woman','student','5','2014-03-20');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('10', 'Alexandrov','Andrew','Semenovich','184');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('10', '10','2','1','1975-9-05','man','deputate','13','2009-11-20');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('11', 'Semenov','Ivan','Ivanovich','4425');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('11', '11','1','0','1983-9-14','man','non-working','30','2010-03-05');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('12', 'Alexandrov','Peter','Andreevich','2183');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('12', '12','4','0','1997-6-01','man','driver','18','2013-01-08');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('13', 'Peterov','Ivan','Alexandrovich','9311');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('13', '13','4','0','1982-03-25','man','student','34','2008-01-20');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('14', 'Andreev','Alexandr','Semenovich','620');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('14', '14','3','1','1997-11-08','man','student','15','2008-03-08');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('15', 'Peterov','Andrew','Andreevich','47');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('15', '15','2','0','1982-6-14','man','RNPC','1','2009-11-01');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('16', 'Peterova','Maria','Andreevna','5874');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('16', '16','2','1','1961-03-01','woman','non-working','1','2009-11-25');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('17', 'Ivanova','Elena','Andreevna','9804');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('17', '17','2','0','1979-6-17','woman','non-working','10','2013-01-14');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('18', 'Alexandrova','Anna','Peterovna','2053');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('18', '18','1','1','1988-03-01','woman','driver','31','2011-9-01');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('19', 'Andreeva','Anna','Alexandrovna','5358');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('19', '19','1','0','1980-11-05','woman','RNPC','40','2010-6-14');
INSERT INTO persons (person_id, fam, name, otch, contact_id) VALUES ('20', 'Ivanova','Galina','Ivanovna','5703');
INSERT INTO donors (donor_id,person_id,bllood_gr, rf, born, sex, work, passed, lastpass) VALUES ('20', '20','4','1','1992-9-25','woman','teacher','25','2013-6-20');
